name: Deploy on Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - closed
  push:
    branches:
      - main
jobs:
  deploy:
    if: github.repository == 'tedxgecrit/tedxgecrit23'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install vercel cli
        run: npm install -global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN2 }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN2 }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --name "ghostchats" --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN2 }}
